run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - examples

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck is a go vet on steroids
    - typecheck     # Type check
    - unused        # Check for unused constants, variables, functions and types
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gosec         # Security-focused linter
    - bodyclose     # Check for unclosed HTTP response bodies
    - noctx         # Check for not using context in requests
    - goconst       # Find repeated strings that could be constants
    - gocritic      # Most opinionated Go source code linter
    - gocyclo       # Computes and checks cyclomatic complexity
    - godot         # Check if comments end in period
    - goprintffuncname # Check printf-like function names
    - nilerr        # Find code that returns nil even if it checks the error

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: errorf
        disabled: false

  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck)
      - G304  # File path provided as taint input (false positives)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

    # Exclude known false positives
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude error checks in defer statements
    - text: "Error return value of.*is not checked"
      linters:
        - errcheck
      source: "defer "

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
